add possibility to filter user by authorities
xm-online/xm-uaa pull request #208
Opened 2022-11-15 13:57 UTC by ArturRoze

2022-11-16 08:16 UTC, sergeysenja1992 requested changes
Pls add tests

2022-11-16 15:19 UTC, ArturRoze commented
> Pls add tests

Done

2022-11-16 15:35 UTC, sergeysenja1992 approved these changes

2022-11-17 08:15 UTC, major13ua approved these changes

2022-11-17 08:15 UTC, merged